version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  database:
    image: cecemel/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
  deltanotifier:
    image: cecemel/delta-notifier:0.2.0-beta.2
    volumes:
      - ./config/delta:/config
  file:
    image: semtech/mu-file-service:3.2.0
    volumes:
      - ./data/files:/share
  delta-producer-json-diff-file-publisher-physical-files:
    image: lblod/delta-producer-json-diff-file-publisher:0.3.0
    environment:
      MAX_BODY_SIZE: "50mb"
      ERROR_GRAPH: "http://mu.semte.ch/graphs/errors"
      RELATIVE_FILE_PATH: "deltas/physical-files"
      PUBLISHER_URI: "http://data.lblod.info/services/delta-production-json-diff-file-manager-physical-files"
      PUBLICATION_GRAPH: 'http://mu.semte.ch/graphs/uploaded-files'
      FILES_GRAPH: 'http://mu.semte.ch/graphs/json-diff-files'
      DELTA_INTERVAL_MS: 10000
      PRETTY_PRINT_DIFF_JSON: "true"
    volumes:
      - ./data/files:/share
