version: '3.7'
services:
  identifier:
    ports:
      - 80:80
  virtuoso:
    ports:
      - 8890:8890
  database:
    environment:
    environment:
      LOG_OUTGOING_SPARQL_QUERIES : "true"
      INSPECT_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      INSPECT_INCOMING_SPARQL_QUERIES: "true"
      LOG_SERVER_CONFIGURATION: "true"
      LOG_ACCESS_RIGHTS : "true"
      INSPECT_ACCESS_RIGHTS_PROCESSING : "true"
      LOG_DELTA_MESSAGES : "true"
      LOG_DELTA_CLIENT_COMMUNICATION : "true"
      LOG_TEMPLATE_MATCHER_PERFORMANCE : "true"
      LOG_OUTGOING_SPARQL_QUERY_RESPONSES : "true"
      INSPECT_OUTGOING_SPARQL_QUERY_RESPONSES : "true"
